INSERT INTO public.categories ("name")
VALUES
('Arhitektura, graditeljstvo i geodezija'),
('Biotehnologija i farmacija'),
('Elektrotehnika, strojarstvo i brodogradnja'),
('Financije, računovodstvo i osiguranja'),
('Geologija, rudarstvo i metalurgija'),
('Informatika i telekomunikacije'),
('Instalacije, održavanje i popravak'),
('Ljepota, zabava i rekreacija'),
('Marketing i PR'),
('Mediji i izdavaštvo'),
('Obrazovanje i znanost'),
('Poljoprivreda, šumarstvo i ribarstvo'),
('Poslovna suradnja'),
('Pravo i administracija'),
('Prodaja'),
('Proizvodnja i zanatske usluge'),
('Sigurnost i zaštita'),
('Transport, skladištenje i logistika'),
('Turizam i ugostiteljstvo'),
('Umjetnost, kultura i dizajn'),
('Upravljanje, organizacija i savjetovanje'),
('Zdravstvo, socijalna skrb i njega');