INSERT INTO public.municipalities ("name", "county_id")
VALUES
('Bedenica', 1),
('Bistra', 1),
('Brckovljani', 1),
('Brdovec', 1),
('Dubrava', 1),
('Dubravica', 1),
('Dugo Selo', 1),
('Farkaševac', 1),
('Gradec', 1),
('Ivanić-Grad', 1),
('Jakovlje', 1),
('Jastrebarsko', 1),
('Klinča Sela', 1),
('Kloštar Ivanić', 1),
('Krašić', 1),
('Kravarsko', 1),
('Križ', 1),
('Luka', 1),
('Marija Gorica', 1),
('Orle', 1),
('Pisarovina', 1),
('Pokupsko', 1),
('Preseka', 1),
('Pušća', 1),
('Rakovec', 1),
('Rugvica', 1),
('Samobor', 1),
('Stupnik', 1),
('Sveta Nedelja', 1),
('Sveti Ivan Zelina', 1),
('Velika Gorica', 1),
('Vrbovec', 1),
('Zaprešić', 1),
('Žumberak', 1),
('Bedekovčina', 2),
('Budinščina', 2),
('Desinić', 2),
('Donja Stubica', 2),
('Đurmanec', 2),
('Gornja Stubica', 2),
('Hrašćina', 2),
('Hum na Sutli', 2),
('Jesenje', 2),
('Klanjec', 2),
('Konjščina', 2),
('Kraljevec na Sutli', 2),
('Krapina', 2),
('Krapinske Toplice', 2),
('Kumrovec', 2),
('Lobor', 2),
('Mače', 2),
('Marija Bistrica', 2),
('Mihovljan', 2),
('Novi Golubovec', 2),
('Oroslavje', 2),
('Petrovsko', 2),
('Pregrada', 2),
('Radoboj', 2),
('Stubičke Toplice', 2),
('Sveti Križ Začretje', 2),
('Tuhelj', 2),
('Veliko Trgovišće', 2),
('Zabok', 2),
('Zagorska Sela', 2),
('Zlatar', 2),
('Zlatar Bistrica', 2),
('Donji Kukuruzari', 3),
('Dvor', 3),
('Glina', 3),
('Gvozd', 3),
('Hrvatska Dubica', 3),
('Hrvatska Kostajnica', 3),
('Jasenovac', 3),
('Kutina', 3),
('Lekenik', 3),
('Lipovljani', 3),
('Majur', 3),
('Martinska Ves', 3),
('Novska', 3),
('Petrinja', 3),
('Popovača', 3),
('Sisak', 3),
('Sunja', 3),
('Topusko', 3),
('Velika Ludina', 3),
('Barilović', 4),
('Bosiljevo', 4),
('Cetingrad', 4),
('Draganić', 4),
('Generalski Stol', 4),
('Josipdol', 4),
('Kamanje', 4),
('Krnjak', 4),
('Lasinja', 4),
('Netretić', 4),
('Plaški', 4),
('Rakovica', 4),
('Ribnik', 4),
('Saborsko', 4),
('Tounj', 4),
('Vojnić', 4),
('Žakanje', 4),
('Duga Resa', 4),
('Karlovac', 4),
('Ogulin', 4),
('Ozalj', 4),
('Slunj', 4),
('Brinje', 5),
('Donji Lapac', 5),
('Gospić', 5),
('Karlobag', 5),
('Lovinac', 5),
('Novalja', 5),
('Otočac', 5),
('Perušić', 5),
('Plitvička Jezera', 5),
('Senj', 5),
('Udbina', 5),
('Vrhovine', 5),
('Bednja', 6),
('Beretinec', 6),
('Breznica', 6),
('Breznički Hum', 6),
('Cestica', 6),
('Donja Voća', 6),
('Gornji Kneginec', 6),
('Jalžabet', 6),
('Ivanec', 6),
('Klenovnik', 6),
('Ljubešćica', 6),
('Lepoglava', 6),
('Ludbreg', 6),
('Mali Bukovec', 6),
('Martijanec', 6),
('Maruševec', 6),
('Novi Marof', 6),
('Petrijanec', 6),
('Sračinec', 6),
('Sveti Đurđ', 6),
('Sveti Ilija', 6),
('Trnovec Bartolovečki', 6),
('Varaždin', 6),
('Varaždinske Toplice', 6),
('Veliki Bukovec', 6),
('Vidovec', 6),
('Vinica', 6),
('Visoko', 6),
('Drnje', 7),
('Đelekovec', 7),
('Đurđevac', 7),
('Ferdinandovac', 7),
('Gola', 7),
('Gornja Rijeka', 7),
('Hlebine', 7),
('Kalinovac', 7),
('Kalnik', 7),
('Kloštar Podravski', 7),
('Koprivnički Bregi', 7),
('Koprivnica', 7),
('Koprivnički Ivanec', 7),
('Legrad', 7),
('Molve', 7),
('Novigrad Podravski', 7),
('Novo Virje', 7),
('Peteranec', 7),
('Podravske Sesvete', 7),
('Rasinja', 7),
('Sokolovac', 7),
('Sveti Ivan Žabno', 7),
('Sveti Petar Orehovec', 7),
('Virje', 7),
('Križevci', 7),
('Berek', 8),
('Bjelovar', 8),
('Čazma', 8),
('Daruvar', 8),
('Dežanovac', 8),
('Đulovac', 8),
('Garešnica', 8),
('Grubišno Polje', 8),
('Hercegovac', 8),
('Ivanska', 8),
('Kapela', 8),
('Končanica', 8),
('Nova Rača', 8),
('Rovišće', 8),
('Severin', 8),
('Sirač', 8),
('Šandrovac', 8),
('Štefanje', 8),
('Velika Pisanica', 8),
('Velika Trnovitica', 8),
('Veliki Grđevac', 8),
('Veliko Trojstvo', 8),
('Zrinski Topolovac', 8),
('Bakar', 9),
('Baška', 9),
('Brod Moravice', 9),
('Cres', 9),
('Crikvenica', 9),
('Čabar', 9),
('Čavle', 9),
('Delnice', 9),
('Dobrinj', 9),
('Fužine', 9),
('Jelenje', 9),
('Kastav', 9),
('Klana', 9),
('Kostrena', 9),
('Kraljevica', 9),
('Krk', 9),
('Lokve', 9),
('Lopar', 9),
('Lovran', 9),
('Mali Lošinj', 9),
('Malinska-Dubašnica', 9),
('Matulji', 9),
('Mošćenička Draga', 9),
('Mrkopalj', 9),
('Novi Vinodolski', 9),
('Omišalj', 9),
('Opatija', 9),
('Punat', 9),
('Rab', 9),
('Ravna Gora', 9),
('Rijeka', 9),
('Skrad', 9),
('Vinodolska općina', 9),
('Viškovo', 9),
('Vrbnik', 9),
('Vrbovsko', 9),
('Crnac', 10),
('Čačinci', 10),
('Čađavica', 10),
('Gradina', 10),
('Lukač', 10),
('Mikleuš', 10),
('Nova Bukovica', 10),
('Orahovica', 10),
('Pitomača', 10),
('Slatina', 10),
('Sopje', 10),
('Suhopolje', 10),
('Špišić Bukovica', 10),
('Virovitica', 10),
('Voćin', 10),
('Zdenci', 10),
('Brestovac', 11),
('Čaglin', 11),
('Jakšić', 11),
('Kaptol', 11),
('Kutjevo', 11),
('Lipik', 11),
('Pakrac', 11),
('Pleternica', 11),
('Požega', 11),
('Velika', 11),
('Bebrina', 12),
('Brodski Stupnik', 12),
('Bukovlje', 12),
('Cernik', 12),
('Davor', 12),
('Donji Andrijevci', 12),
('Dragalić', 12),
('Garčin', 12),
('Gornja Vrba', 12),
('Gornji Bogićevci', 12),
('Gundinci', 12),
('Klakar', 12),
('Nova Gradiška', 12),
('Nova Kapela', 12),
('Okučani', 12),
('Oprisavci', 12),
('Oriovac', 12),
('Podcrkavlje', 12),
('Rešetari', 12),
('Sibinj', 12),
('Sikirevci', 12),
('Slavonski Brod', 12),
('Slavonski Šamac', 12),
('Stara Gradiška', 12),
('Staro Petrovo Selo', 12),
('Velika Kopanica', 12),
('Vrbje', 12),
('Vrpolje', 12),
('Benkovac', 13),
('Bibinje', 13),
('Biograd na Moru', 13),
('Galovac', 13),
('Gračac', 13),
('Jasenice', 13),
('Kali', 13),
('Kolan', 13),
('Kukljica', 13),
('Lišane Ostrovičke', 13),
('Nin', 13),
('Novigrad', 13),
('Obrovac', 13),
('Pag', 13),
('Pakoštane', 13),
('Pašman', 13),
('Polača', 13),
('Poličnik', 13),
('Posedarje', 13),
('Povljana', 13),
('Preko', 13),
('Privlaka', 13),
('Ražanac', 13),
('Sali', 13),
('Stankovci', 13),
('Starigrad', 13),
('Sukošan', 13),
('Sveti Filip i Jakov', 13),
('Škabrnja', 13),
('Tkon', 13),
('Vir', 13),
('Vrsi', 13),
('Zadar', 13),
('Zemunik Donji', 13),
('Antunovac', 14),
('Beli Manastir', 14),
('Belišće', 14),
('Bilje', 14),
('Bizovac', 14),
('Čeminac', 14),
('Čepin', 14),
('Darda', 14),
('Donja Motičina', 14),
('Donji Miholjac', 14),
('Draž', 14),
('Drenje', 14),
('Đakovo', 14),
('Đurđenovac', 14),
('Erdut', 14),
('Ernestinovo', 14),
('Feričanci', 14),
('Gorjani', 14),
('Jagodnjak', 14),
('Kneževi Vinogradi', 14),
('Koška', 14),
('Levanjska Varoš', 14),
('Magadenovac', 14),
('Marijanci', 14),
('Našice', 14),
('Osijek', 14),
('Petlovac', 14),
('Petrijevci', 14),
('Podgorač', 14),
('Podravska Moslavina', 14),
('Popovac', 14),
('Punitovci', 14),
('Satnica Đakovačka', 14),
('Semeljci', 14),
('Strizivojna', 14),
('Šodolovci', 14),
('Trnava', 14),
('Valpovo', 14),
('Viljevo', 14),
('Viškovci', 14),
('Vladislavci', 14),
('Vuka', 14),
('Blato', 15),
('Dubrovačko primorje', 15),
('Dubrovnik', 15),
('Janjina', 15),
('Konavle', 15),
('Korčula', 15),
('Kula Norinska', 15),
('Lastovo', 15),
('Lumbarda', 15),
('Metković', 15),
('Mljet', 15),
('Opuzen', 15),
('Orebić', 15),
('Ploče', 15),
('Pojezerje', 15),
('Slivno', 15),
('Smokvica', 15),
('Ston', 15),
('Trpanj', 15),
('Vela Luka', 15),
('Zažablje', 15),
('Župa dubrovačka', 15),
('Bilice', 16),
('Biskupija', 16),
('Civljane', 16),
('Drniš', 16),
('Ervenik', 16),
('Kijevo', 16),
('Kistanje', 16),
('Knin', 16),
('Murter-Kornati', 16),
('Pirovac', 16),
('Primošten', 16),
('Promina', 16),
('Rogoznica', 16),
('Ružić', 16),
('Skradin', 16),
('Šibenik', 16),
('Tisno', 16),
('Tribunj', 16),
('Unešić', 16),
('Vodice', 16),
('Andrijaševci', 17),
('Babina Greda', 17),
('Bogdanovci', 17),
('Borovo', 17),
('Bošnjaci', 17),
('Cerna', 17),
('Drenovci', 17),
('Gradište', 17),
('Gunja', 17),
('Ilok', 17),
('Ivankovo', 17),
('Jarmina', 17),
('Lovas', 17),
('Markušica', 17),
('Negoslavci', 17),
('Nijemci', 17),
('Nuštar', 17),
('Otok', 17),
('Privlaka', 17),
('Stari Jankovci', 17),
('Stari Mikanovci', 17),
('Štitar', 17),
('Tompojevci', 17),
('Tordinci', 17),
('Tovarnik', 17),
('Trpinja', 17),
('Vinkovci', 17),
('Vođinci', 17),
('Vrbanja', 17),
('Vukovar', 17),
('Županja', 17),
('Baška Voda', 18),
('Bol', 18),
('Brela', 18),
('Cista Provo', 18),
('Dicmo', 18),
('Dugi Rat', 18),
('Dugopolje', 18),
('Gradac', 18),
('Hrvace', 18),
('Hvar', 18),
('Imotski', 18),
('Jelsa', 18),
('Kaštela', 18),
('Klis', 18),
('Komiža', 18),
('Lećevica', 18),
('Lokvičići', 18),
('Lovreć', 18),
('Makarska', 18),
('Marina', 18),
('Milna', 18),
('Muć', 18),
('Nerežišća', 18),
('Okrug', 18),
('Omiš', 18),
('Otok', 18),
('Podbablje', 18),
('Podgora', 18),
('Podstrana', 18),
('Postira', 18),
('Prgomet', 18),
('Primorski Dolac', 18),
('Proložac', 18),
('Pučišća', 18),
('Runovići', 18),
('Seget', 18),
('Selca', 18),
('Sinj', 18),
('Solin', 18),
('Split', 18),
('Stari Grad', 18),
('Sućuraj', 18),
('Supetar', 18),
('Sutivan', 18),
('Šestanovac', 18),
('Šolta', 18),
('Trilj', 18),
('Trogir', 18),
('Tučepi', 18),
('Vis', 18),
('Vrgorac', 18),
('Vrlika', 18),
('Zadvarje', 18),
('Zagvozd', 18),
('Zmijavci', 18),
('Bale-Valle', 19),
('Barban', 19),
('Brtonigla-Verteneglio', 19),
('Buje-Buie', 19),
('Buzet', 19),
('Cerovlje', 19),
('Fažana-Fasana', 19),
('Funtana-Fontane', 19),
('Gračišće', 19),
('Grožnjan-Grisignana', 19),
('Kanfanar', 19),
('Karojba', 19),
('Kaštelir-Labinci-Castelliere-S. Domenica', 19),
('Kršan', 19),
('Labin', 19),
('Lanišće', 19),
('Ližnjan-Lisignano', 19),
('Lupoglav', 19),
('Marčana', 19),
('Medulin', 19),
('Motovun-Montona', 19),
('Novigrad-Cittanova', 19),
('Oprtalj-Portole', 19),
('Pazin', 19),
('Pićan', 19),
('Poreč-Parenzo', 19),
('Pula-Pola', 19),
('Raša', 19),
('Rovinj-Rovigno', 19),
('Sveta Nedelja', 19),
('Sveti Lovreč', 19),
('Sveti Petar u Šumi', 19),
('Svetvinčenat', 19),
('Tar-Vabriga-Torre Abrega', 19),
('Tinjan', 19),
('Umag-Umago', 19),
('Višnjan-Visignano', 19),
('Vižinada-Visinada', 19),
('Vodnjan-Dignano', 19),
('Vrsar-Orsera', 19),
('Žminj', 19),
('Belica', 20),
('Čakovec', 20),
('Dekanovec', 20),
('Domašinec', 20),
('Donja Dubrava', 20),
('Donji Kraljevec', 20),
('Donji Vidovec', 20),
('Goričan', 20),
('Gornji Mihaljevec', 20),
('Kotoriba', 20),
('Mala Subotica', 20),
('Mursko Središće', 20),
('Nedelišće', 20),
('Orehovica', 20),
('Podturen', 20),
('Prelog', 20),
('Pribislavec', 20),
('Selnica', 20),
('Strahoninec', 20),
('Sveta Marija', 20),
('Sveti Juraj na Bregu', 20),
('Sveti Martin na Muri', 20),
('Šenkovec', 20),
('Štrigova', 20),
('Vratišinec', 20),
('Zagreb', 21);